'use server';
/**
 * @fileOverview An AI agent that generates sales insights for boutique owners.
 *
 * - generateAiSalesInsights - A function that handles the sales insights generation process.
 * - AiSalesInsightsGeneratorInput - The input type for the generateAiSalesInsights function.
 * - AiSalesInsightsGeneratorOutput - The return type for the generateAiSalesInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiSalesDataEntrySchema = z.object({
  productId: z.string().describe('Unique identifier for the product.'),
  productName: z.string().describe('Name of the product.'),
  quantity: z.number().int().positive().describe('Quantity of the product sold.'),
  price: z.number().positive().describe('Price per unit of the product.'),
  saleDate: z.string().datetime().describe('Timestamp of the sale in ISO 8601 format.'),
  paymentMethod: z.enum(['Cash', 'Bank Transfer']).describe('Method of payment for the sale.'),
});
export type AiSalesDataEntry = z.infer<typeof AiSalesDataEntrySchema>;

const AiSalesInsightsGeneratorInputSchema = z.object({
  salesData: z.array(AiSalesDataEntrySchema).describe('An array of sales transactions.'),
  timeframe: z
    .string()
    .describe(
      'The timeframe for which insights are requested (e.g., "last 7 days", "this month", "daily", "weekly", "monthly").'
    ),
});
export type AiSalesInsightsGeneratorInput = z.infer<
  typeof AiSalesInsightsGeneratorInputSchema
>;

const AiSalesInsightsGeneratorOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the sales performance for the given timeframe.'),
  keyTrends: z.array(z.string()).describe('A list of significant sales trends identified.'),
  bestSellingProducts: z
    .array(
      z.object({
        productName: z.string().describe('Name of the best-selling product.'),
        salesVolume: z.number().int().positive().describe('Total quantity sold for this product.'),
        totalRevenue: z.number().positive().describe('Total revenue generated by this product.'),
      })
    )
    .describe('A list of the best-performing products.'),
  actionableRecommendations: z
    .array(z.string())
    .describe('Actionable business recommendations based on the sales insights to maximize revenue.'),
});
export type AiSalesInsightsGeneratorOutput = z.infer<
  typeof AiSalesInsightsGeneratorOutputSchema
>;

export async function generateAiSalesInsights(
  input: AiSalesInsightsGeneratorInput
): Promise<AiSalesInsightsGeneratorOutput> {
  return aiSalesInsightsGeneratorFlow(input);
}

const salesInsightsPrompt = ai.definePrompt({
  name: 'salesInsightsPrompt',
  input: {schema: AiSalesInsightsGeneratorInputSchema},
  output: {schema: AiSalesInsightsGeneratorOutputSchema},
  prompt: `You are an expert sales analyst for a boutique clothing store. Your task is to generate concise, actionable insights from the provided sales data.

Analyze the sales data for the timeframe: {{{timeframe}}}.

Identify key sales trends, pinpoint best-performing products, and provide actionable recommendations to maximize revenue.

Sales Data: {{{JSON.stringify salesData}}}`,
});

const aiSalesInsightsGeneratorFlow = ai.defineFlow(
  {
    name: 'aiSalesInsightsGeneratorFlow',
    inputSchema: AiSalesInsightsGeneratorInputSchema,
    outputSchema: AiSalesInsightsGeneratorOutputSchema,
  },
  async input => {
    const {output} = await salesInsightsPrompt(input);
    return output!;
  }
);
